### ISSUE TITLE
do not trust user input

### ISSUE THREAD

**Issue by danmarsden** [Limekiller/moodle-block_openai_questions#1]
the data received from the call here:
https://github.com/Limekiller/moodle-block_openai_questions/blob/main/api/question.php#L34C2-L34C10

is raw unfiltered data submitted by the user - which you then include directly in the API calls without cleaning/filtering it first - can you please add some clean_param() or other style calls before using the vars you get out of the $response var?

Note this is a blocker for plugins db approval.

**Comment by danmarsden** [comment]
it would also be good to see some sanitization of the data coming back from the AI - eg https://github.com/Limekiller/moodle-block_openai_questions/blob/main/generate.php#L92 - can we do any cleaning/sanitisation of that data before using it Moodle?

**Comment by Limekiller** [comment]
Fixed in https://github.com/Limekiller/moodle-block_openai_questions/commit/6e5406e89dac91f05ae040c1d940d58446333258 and https://github.com/Limekiller/moodle-block_openai_questions/commit/00c7e3d96ffaf08a556abdcecff5f1d4322dcf38
